### ISSUE TITLE
Name needs to be changed! 

### ISSUE THREAD

**Issue by KevCaz** [letiR/letiRmisc#3]
The name *letiRmisc* was actually coined by juxtaposing 

1. letiR:  the former name of our group (nice play on words btw),
2. and misc that stands for miscellaneous .

So I am going to do some change to the package so I thought it was a good opportunity to change its name for 
`inSilecoMisc` so it fits well with `inSilecoRef`!

Basically I gonna remove the last trace of letiR :cry: !

**Comment by david-beauchesne** [comment]
I guess we can't get hung up on the past...

**Comment by KevCaz** [comment]
haha

**Comment by KevCaz** [comment]
Done! 

See d6e235e1218bd83228ca86d089c4951b0db47179

As for now, letiRmisc is inSilecoMisc!

**Comment by SteveViss** [comment]
We should pinned this issue forever ;)
